// Shared TypeScript types
// These are the types shared at the hook-component boundary.
// Generated by the Developer agent, consumed by Frontend Engineer.
// Source of truth: spec/features/{feature}/dev-brief.md

// ─── Core entity types ────────────────────────────────────────────────────────
// Add your entity types here as they are defined in ENTITY_MODEL.md

export interface BaseEntity {
  id: number;
  createdAt: Date;
  updatedAt: Date;
}

// ─── Feature types ────────────────────────────────────────────────────────────
// Export feature types from their respective hook files and re-export here
